### ISSUE TITLE
Define work needed to get DPS properly set up for local development

### ISSUE THREAD

**Issue by franklywatson** [dapperlabs/flow-dps#4]
@franklywatson commented on [Tue Feb 15 2022](https://github.com/dapperlabs/flow-internal/issues/1669)

## Context

To date making and testing changes on the DPS has been a slow and cumbersome process requiring the use of large data sets and with limited ability to debug and troubleshoot locally and with no way to avoid the loading of multi-GB files to verify it's functioning. 

This task is to document the tasks required to make developing with DPS very much more straight forward, with a faster cycle time and quick bootstrap for developers. 

## Definition of Done

* An Epic and sub-tasks is created that summarises all the work which needs to be completed to realize the goal of a smoother, simpler, faster development cycles when working with DPS

**Comment by peterargue** [comment]
Epic: https://github.com/dapperlabs/flow-dps/issues/5
